### ISSUE TITLE
CollectionMethod Objectprops crashes

### ISSUE THREAD

**Issue by 0x6d69636b** [BloodHoundAD/SharpHound2#11]
When I try to collect ObjectProps the binary crashes. All other methods are working fine. I tried it under Windows 10, Windows Server 2012 R2 and Windows Server 2016.  I get the same result on all systems.

> PS C:\tmp> .\SharpHound.exe -c Objectprops --Verbose
> Initializing BloodHound at 15:42 on 20.10.2017
> Starting ObjectProps enumeration for example.com
> Waiting for enumeration threads to finish
> Status: 27 objects enumerated (+27 +unendlich/s --- Using 29 MB RAM )
> Waiting for writer thread to finish
> 
> Unhandled Exception: System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Sharphound2.OutputObjects.UserProp.StringToCsvCell(String str)
>    at Sharphound2.OutputObjects.UserProp.ToCsv()
>    at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass16_0.<StartOutputWriter>b__0()
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
>    at Sharphound2.Sharphound.Main(String[] args)
> ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
>    at Sharphound2.OutputObjects.UserProp.StringToCsvCell(String str)
>    at Sharphound2.OutputObjects.UserProp.ToCsv()
>    at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass16_0.<StartOutputWriter>b__0()
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()<---

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/SharpHound/commit/b2f98dc9e5675b5687964a7eaeeb3573fe6b676a
