### ISSUE TITLE
-f / -p flags not working

### ISSUE THREAD

**Issue by cottinghamd** [BloodHoundAD/SharpHound2#13]
Very minor issue. SharpHound help (-?) suggests that I can use -f to specify a CSV Folder path to store CSV files. Additionally it specifies that I can use -p to specify a CSV Prefix.

If I run the following command, the help is displayed, suggesting there is a syntax error:
sharphound.exe -d domain.name -f c:\output\path

However the following command does work:
sharphound.exe -d domain.name --CSVFolder c:\output\path

This is the same issue with -p and --CSVPrefix flags.

**Comment by rvazarkar** [comment]
The short flags were removed a while ago in order to fix some issues with inconsistency and it looks like I forgot to update the help text. Fixing this now
