### ISSUE TITLE
Crash caused when specifying folder path for CSVFolder

### ISSUE THREAD

**Issue by cottinghamd** [BloodHoundAD/SharpHound2#14]
You can cause SharpHound to crash with 'illegal characters' if the folder paths contain a trailing backslash for example:

sharphound.exe -d [domain] --CSVFolder "C:\new folder"
works

sharphound.exe -d [domain] --CSVFolder "C:\new folder\\"
causes a crash

The following crash occurs:

Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path)
   at System.IO.Path.Combine(String path1, String path2)
   at Sharphound2.Cache..ctor(Options opts)
   at Sharphound2.Cache.CreateInstance(Options opts)
   at Sharphound2.Sharphound.Main(String[] args)

Here is a process dump of the crash for analysis:
https://www.dropbox.com/s/8ruboe3hadsvhty/SharpHound.exe_171204_114455.dmp?dl=1

UPDATE: If you escape the last backslash it doesn't crash. For example:

sharphound.exe -d [domain] --CSVFolder "C:\new folder\\\\"

**Comment by rvazarkar** [comment]
This seems to be a bug in the way .NET parses command line arguments...not sure if there's any real way to fix it. See https://github.com/commandlineparser/commandline/issues/43.

I added a check to at least fail gracefully.
