### ISSUE TITLE
System.NullReferenceException in Sharphound2.Utils.ResolveHost(String hostName)

### ISSUE THREAD

**Issue by jbfuzier** [BloodHoundAD/SharpHound2#21]
Hi,

I am having an unhandled exception while running the session collection. It occurs on different PCs.

Here is the stack trace : 

> Exception non gérée : System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName)
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext()
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()
>    --- Fin de la trace de la pile d'exception interne ---
>    à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
>    à System.Threading.Tasks.Task.WaitAll(Task[] tasks)
>    à Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
>    à Sharphound2.Sharphound.Main(String[] args)
> ---> (Inner Exception #0) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName)
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext()
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()<---
> 
> ---> (Inner Exception #1) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName)
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext()
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()<---

With this build https://github.com/BloodHoundAD/SharpHound/files/1816599/Sharphound.zip (the last one from issue #20 ).

**Comment by rvazarkar** [comment]
[Debug.zip](https://github.com/BloodHoundAD/SharpHound/files/1841840/Debug.zip)

Hello again! Can you run this build with both files in the zip file in the same directory. It might fix your issue, but if not, it'll give me a line number to work with

**Comment by jbfuzier** [comment]
Long time no see :) 
Thanks, I am gonna try this build

**Comment by jbfuzier** [comment]
Still crashing...

> Exception non gérée : System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName) dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Utils.cs:ligne 85
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\SessionHelpers.cs:ligne 141
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:ligne 707
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()
>    --- Fin de la trace de la pile d'exception interne ---
>    à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
>    à System.Threading.Tasks.Task.WaitAll(Task[] tasks)
>    à Sharphound2.Enumeration.EnumerationRunner.StartEnumeration() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:ligne 483
>    à Sharphound2.Sharphound.Main(String[] args) dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Sharphound.cs:ligne 554
> ---> (Inner Exception #0) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName) dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Utils.cs:ligne 85
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\SessionHelpers.cs:ligne 141
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:ligne 707
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()<---
> 
> ---> (Inner Exception #1) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName) dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Utils.cs:ligne 85
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\SessionHelpers.cs:ligne 141
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:ligne 707
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()<---
> 
> ---> (Inner Exception #2) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName) dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Utils.cs:ligne 85
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\SessionHelpers.cs:ligne 141
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:ligne 707
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()<---
> 
> ---> (Inner Exception #3) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName) dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Utils.cs:ligne 85
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\SessionHelpers.cs:ligne 141
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:ligne 707
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()<---
> 
> ---> (Inner Exception #4) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName) dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Utils.cs:ligne 85
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\SessionHelpers.cs:ligne 141
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:ligne 707
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()<---
> 
> ---> (Inner Exception #5) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à Sharphound2.Utils.ResolveHost(String hostName) dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Utils.cs:ligne 85
>    à Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\SessionHelpers.cs:ligne 141
>    à Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0() dans C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:ligne 707
>    à System.Threading.Tasks.Task.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()<---
> 
> Status: 125613 objects enumerated (+0 10,79242/s --- Using 463 MB RAM )
>

**Comment by rvazarkar** [comment]
Should be fixed in the most recent commit. You can compile it yourself, or let me know and I can drop you a zip file here.
