### ISSUE TITLE
Sharphound returning incomplete results for Localgroup

### ISSUE THREAD

**Issue by just1fi3d** [BloodHoundAD/SharpHound2#22]
I"m getting partial results back when running sharphound vs bloodhound (and what is actually in the Administrators group). With the old powershell script I get all users in the Administrators group but with sharphound I only get a subset of that. Here are the commands I'm running.

Bloodhound
`PS > Invoke-BloodHound -CollectionMethod LocalGroup -ComputerName \'**removed**\' -CSVFolder C:\Data\ -CSVPrefix "bloodhound"`

Sharphound:
`SharpHound.exe --SkipPing -c LocalGroup --ComputerFile host.txt --CSVFolder C:\Data --SVPrefix sharphound`

The one thing I did notices is that for sharphound all of the objects returned are in the same domain but objects for other domains under the same parent are not returned. The bloodhound ps1 did return the objects for other domains without issue.

**Comment by rvazarkar** [comment]
Are you using the most recent SharpHound build released with 1.5? We made changes to local group collection recently. 

I tested locally, and cross domain lookups seem to work fine for local admins.

If you're on 1.5, I can give you some guidance on how to try and debug it.

**Comment by just1fi3d** [comment]
Ya, I just grabbed newest one from [here ](https://github.com/BloodHoundAD/BloodHound/tree/master/Ingestors) and tried again and had the same issue. Let me know what I should do debugging wise and I will give it a shot.

**Comment by rvazarkar** [comment]
I would go ahead and add a single computer where you know the problem is into a new text file. Then run with the ComputerFile parameter, and using the exe, add **--Debug** to your execution flags. It'll give you a lot more information and you can start narrowing down why SharpHound is throwing out that data

**Comment by just1fi3d** [comment]
ok, I'm seeing `Debug: No entry found` in the ouput for the ones that don't come back. Sanitized output is attached.
[sharphound.txt](https://github.com/BloodHoundAD/SharpHound/files/1861504/sharphound.txt)

**Comment by just1fi3d** [comment]
Looks like it is looking for all SIDs in the same child domain and not looking in any others.

**Comment by rvazarkar** [comment]
Can you remove your BloodHound.bin file and re-run it?

**Comment by just1fi3d** [comment]
Ok, Did that got about the same results as far as I can tell.
[sharphound1.txt](https://github.com/BloodHoundAD/SharpHound/files/1862712/sharphound1.txt)

**Comment by rvazarkar** [comment]
I'm not really sure how to debug this remotely with all the information censored out. We determine the domain to search by looking at the SID of the object that we're searching for. Apparently in your setup, its finding the wrong domain for whatever reason. 

If you can dig through the code and find the issue, I'll be more than happy to accept changes or even just guidance on how to fix the issue. I can't see anything in the code that would cause the issue you're having though, and I'm unable to replicate it myself.

**Comment by rvazarkar** [comment]
Also, I just noticed you're using a ComputerName parameter in the powershell script, which isn't a supported parameter, so probably wont do anything.

**Comment by rvazarkar** [comment]
The relevant code is in [this file](https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Enumeration/LocalAdminHelpers.cs)

Particularly, the issue seems to be somewhere in [this function](https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Enumeration/LocalAdminHelpers.cs#L241)

**Comment by just1fi3d** [comment]
Ok, I'm going to take a crack at troubleshooting this. I'll get back to you when I figure it out.

**Comment by just1fi3d** [comment]
Alright, it looks like I was facing two issues one is that I'm dumb and didn't see the --searchforest flag. It seemed like this behavior happened by default in the powershell script so I missed it. However, it does appear that with this flag (and --localgroup at least, haven't tested with others) even after an object has been identified as under one domain it still continues to search other domains for the same SID. Is this intended behavior? 

Also, it would be helpful to have a flag that allowed a text file with ordered and specified domains to search in similar to the --ComputerFile flag.

Second issue, is that if an object can't be found by querying the directory it is skipped and not returned to the user per line 356 in localadminhelpers. The object may exist in the domain but have restricted view ACLs or may not be viewable for some other reason. It would be helpful to have a flag that allowed sharphound to return object names and domains gather from a computer even if they cannot be found in the directory similar to how the powershell script returned object@unknown if it couldn't be found. I did notice that resolvedObjects on line 273 has shorthand domain info about the objects. It may be useful to return that info even if you can't get full or any information from the directory.

Let me know if you want me to put in separate feature or bug requests for these or need more info and I can do that.

**Comment by rvazarkar** [comment]
I don't understand what you mean by the first part. So the logic should look something like this for local groups:

* Grab data from the NetLocalGroupGetMembers function
* For each entry found, make sure its not a local account or a null account
* Take the SID returned by the API and lookup the corresponding domain using the SID
* Do an LDAP search in that domain for the object found and resolve it to the bloodhound display name

SearchForest should not affect this at all. The logic to determine which domain is used is in in the function [here](https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Utils.cs#L230) which is passed to the searcher in the function [here](https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Enumeration/LocalAdminHelpers.cs#L355). 

I might be misunderstanding what you're saying though.

As for the second part, we made the decision to drop UNKNOWN domains because it causes issues with data reliability. I dont think we considered restricted ACEs when we made that decision so we might revisit it. On the other hand, it introduces problems in pathfinding, so I'm not sure if we'll bring that model back.

**Comment by just1fi3d** [comment]
We did some more testing and here is what we found. I think that the problem is that we are starting in a child domain and cannot search up.


Our computer, the current user, and the server we are running this against are in a.company.com.
The AD group(which is in the Local Admin group of our server) we are querying is in company.com

SharpHound gets the dSID from the SID of the group.

SharpHound checks dSID(for company.com) against _cache (which currently contains only our subdomain, a.company.com) and it unable to get a result.

Utils.cs 416: It then opens a GC connection to domainName (which is currently null)
Utils.cs 534: tries to set targetDomain bu calling GetDomain(domainName).

Utils.cs 611 (GetDomain method): sets key = domainName or "UNIQUENULL" if domainName is null.  (our key became UNIQUENULL since domainName was null.)

Utils.cs 615: From domainCache, it retrieves the Value for "UNIQUENULL" (which is a.company.com).

Utils.cs 617: domainObj becomes a.company.com

Utils.cs 534: targetDomain becomes a.company.com
Utils.cs 541: Initiate LDAPConnection to a.company.com 

Utils.cs 416: Our GC connection is to a.company.com
Utils.cs 424: Makes LDAP Search request for the SID (of the group)

Utils.cs 556:sets targetDomain, like above, sets it to a.company.com
Utils.cs 564: domainName set to a.company.com
Utils.cs 565: sets adsPath to DC=a,DC=company,DC=com

Utils.cs 573: returns the LDAPSearch
Utils.cs 424: request is the LDAPSearch query

Utils.cs 451: Sends the query to LDAP (with LDAP server as a.company.com)
Utils.cs 463: Enumerates over results (there are no results, because the wrong domain was queried)
Utils.cs 471: Exits because there were no entries

Utils.cs 246: entry is null because search returned no results.

Utils.cs 254: Makes another call to LDAP, this time searching for securityidentifier instead of objectsid.  No results returned again.

Utils.cs 260: No SID found because both LDAP queries failed. Ends execution of SidToDomainName.

Utils.cs 355: SidToDisplay(sid, null(the result of above),AdminsProps,"group") called

Utils.cs 281(SidtoDisplay):
Utils.cs 307: Since it was not found it cache, Queries LDAP for objectidSID=sid (again, we did this same query before), returns null
Utils.cs 312: No entry found.

LocalAdminHekos.cs 356: resolvedName is null because of failed LDAP Search.



I believe that because we are in a child domain(a.company.com), there is no object with objectSID=[parentDomain SID]. Maybe the fix would be to add the SID of all domains to the __cache.

**Comment by rvazarkar** [comment]
Ahhhh, great catch and this is super thorough! Nice job! I'll see if I can come up with a better solution for this, and I didn't think about that interaction with the various functions. 

Maybe theres a better way to resolve a domain sid to the domain name

**Comment by rvazarkar** [comment]
It doesn't really make sense that the SID of the parent domain isn't in the global catalog though, thats whats throwing me off. When SidToDomainName is called, it should see the SID is not in the cache, and query the global catalog to look for the domain name from there, which seems to be missing from your rundown. 

```Utils.cs 451: Sends the query to LDAP (with LDAP server as a.company.com)
Utils.cs 463: Enumerates over results (there are no results, because the wrong domain was queried)
Utils.cs 471: Exits because there were no entries

Utils.cs 246: entry is null because search returned no results.

Utils.cs 254: Makes another call to LDAP, this time searching for securityidentifier instead of objectsid. No results returned again.
```


This part should be returning the name of the parent domain. Its not querying the wrong domain, it's querying the global catalog of your current domain, which should absolutely have the parent domain's sid. I'm still going to look into a better way to resolving this if I can, but I'm still having trouble figuring out why its not working in your particular environment.

**Comment by just1fi3d** [comment]
Hmm is there an LDAP query I could run that would help trouble shoot this or maybe somewhere in particular that debug values would help from?

**Comment by rvazarkar** [comment]
Try this build

[Release.zip](https://github.com/BloodHoundAD/SharpHound/files/1904089/Release.zip)

**Comment by just1fi3d** [comment]
I'm away from my pc for the weekend but I'll give it a shot on Monday.

**Comment by just1fi3d** [comment]
I tried out the new build and it looks like, from a results perspective at least, it is getting the right information back. So you can probably close this issue out now.

I still am not getting back objects that are @UNKNOWN or ones that have reestricted ACEs but it sounds like that was a design decision when moving to sharphound. still would be nice to have the option of getting them know that they might cause issues just for informational completeness.


Thanks for the help with this!
