### ISSUE TITLE
Can't connect to LDAP

### ISSUE THREAD

**Issue by CodingFree** [BloodHoundAD/SharpHound2#28]
Hello,

I am trying to ocnnect to my Active Directory server from a remote client. I am using the following options:

`Invoke-BloodHound -CollectionMethod All -Domain example.com -Credential $credential -DomainController fqdn.example.com -Verbose`

Where $credential was created in two possible ways:

- $credential = New-Object System.Management.Automation.PSCredential($username,$password)
- $credential = Get-Credential

In any case, I can't connect to the LDAP service of my Active Diretory:

> Unable to contact domain example.com
> LDAP connection test failed, probably can't contact domain

The domain name can be resolved properly and I verified that the ports (389 and 636) are opened and reachable.

I can't connect to LDAP neither authenticated nor anonymously.

What is going wrong?

**Comment by liamcs98** [comment]
I had this same-ish problem. The weird thing is that I could do a scan against one domain, however not other trusted domains in the forest...until I did "-SearchForest" which worked perfectly! 

For your problem, try doing a `-SearchForest`, then maybe do a run as (see below), all with -verbose flag. 

`runas /netonly /user:bestdomain.local\Administrator powershell.exe`

**Comment by rvazarkar** [comment]
Runas /netonly is the preferred way. 

We've added the LDAPUser and LDAPPassword parameters in 2.0 as well

**Comment by webr0ck** [comment]
> Runas /netonly is the preferred way.
--- it does not work.
work only runas /user
> 
> We've added the LDAPUser and LDAPPassword parameters in 2.0 as well

LDAPUser and LDAPPassword doesn't work, if you use Sharphound at a computer(user) outside of AD.

Problem is in GetDomain:
var context = new DirectoryContext(DirectoryContextType.Domain, domainName);   -  Api tryed connect this your user credentials. You can see that in Wireshark.

If we use LdapUser, LdapPassword true string is:
var context = new DirectoryContext(DirectoryContextType.Domain, domainName, _options.LdapUser, _options.LdapPass);

**Comment by deveshm** [comment]
I think you have to use `DirectoryContextType.DirectoryServer` instead of `DirectoryContextType.Domain`

**Comment by 0xGreen** [comment]
Was this issue ever got resolved ? i am getting the same error

Unable to contact domain example.com
LDAP connection test failed, probably can't contact domain

Tried both sharhound.exe and sharphound.ps1 from a pc outside of DC.

Anyhelp ?

**Comment by rvazarkar** [comment]
Try using the --DisableKerbSigning option

**Comment by surajpkhetani** [comment]
@nsrauf I resolved it by changing the DNS address to that of the target domain.
