### ISSUE TITLE
local_admins.csv does not import

### ISSUE THREAD

**Issue by denied39** [BloodHoundAD/SharpHound2#4]
After running sharphound.exe and trying to import the .csv files, I get a failure on the local_admins.csv. I compared it to the BloodHound PowerShell .csv, and it appears it is missing the header row. I added the header, and the file imported without issue.

**Comment by rvazarkar** [comment]
Strange, can you replicate this issue?

**Comment by denied39** [comment]
This must have been an anomaly. The first two times I ran SharpHound, the header did not appear, but the last two times, it is there. I'll close this out. Thanks for a great tool! The speed improvements are awesome!
