### ISSUE TITLE
Any reason you used RawSecurityDescriptor and not ActiveDirectorySecurity ?

### ISSUE THREAD

**Issue by vletoux** [BloodHoundAD/SharpHound2#43]
When reading your source code, I found out you were using RawSecurityDescriptor which is a little difficult to use.
Are there any reason you used this class instead of ActiveDirectorySecurity?

Indeed, you can get it through:
SearchResult.GetDirectoryEntry().ObjectSecurity

As an alternative, you can use:
ActiveDirectorySecurity sd = new ActiveDirectorySecurity();
sd.SetSecurityDescriptorBinaryForm(binaryData);

Vincent

**Comment by rvazarkar** [comment]
I took your advice. Rewrote the ACL logic using ActiveDirectorySecurity in https://github.com/BloodHoundAD/SharpHound/commit/95e6cb46fc84f12eb873e3cba38f27ecf99d1be4

Thanks Vincent!
