### ISSUE TITLE
SessionLoop Ctrl+C makes session.json file unrecognized

### ISSUE THREAD

**Issue by dtrizna** [BloodHoundAD/SharpHound2#46]
Hi!

Faced problem, where I had to stop loop after some 20+h (with Ctrl+C). This gave me ~30MB sessions.json file, which BloodHound refused to load in, throwing error: "Unrecognized file".

Problem is due to file truncation (wasn't added necessary JSON closing symbols as well as meta tree). I was able to recover file format by parsing this file in python. If anyone faced the same problem, here's the algorithm:
1. Add trailing brackets to file contents: ']}'
2. Parse as json (jsondict = json.loads(file_contents))
3. Count sessions (len(jsondict['sesstions']))
4. Remove trailing '}', add meta tree (,"meta":{"count":<INT>,"type":"sessions"}})

After that BloodHound takes the collected data.

It would be nice to implement Excepction catching logic during SessionLoop, so if Ctrl+C happens, SharpHound performs necessary formatting by itself.

P.S.
Thanks for your work! Beautiful tool!
You're pushing industry in correct direction!

Dmitry

**Comment by rvazarkar** [comment]
Hopefully fixed in https://github.com/BloodHoundAD/SharpHound/commit/1bcd331ebd01bd90e9548cc263adfd45bb95eafe
