### ISSUE TITLE
Syntax change from LocalAdmin to LocalGroup

### ISSUE THREAD

**Issue by hkelley** [BloodHoundAD/SharpHound2#56]
In Sharphound.cs,   the LocalAdmin option (now replaced by "LocalGroup"?) is still in the default options  (and in the version of the PS script being distributed with Bloodhound).

`[OptionArray('c', "CollectionMethod", DefaultValue = new[] {"Default"}, HelpText = "Collection Method (Group, **LocalAdmin**, GPOLocalGroup,`

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/SharpHound/commit/9a976f1c63d24572cf6065f06f02a5780dfa1638
