### ISSUE TITLE
Sharphound ignores inherited "Reset password"-access when applied via OU to "Descendant User objects"

### ISSUE THREAD

**Issue by bravo2day** [BloodHoundAD/SharpHound2#58]
Sharphound.exe: 80F8EDE906A1237FBE6DA83591A66C0A1EA75B0EF1D8CCDDCD67C3BA1498057C (latest)

This works and is written to the csv:
Access:  Write all properties
Applies to: this object and all descendant objects

Access: "Reset password".
Applies to: this object only

The following permissions are ignored and not written to the csv:

Access: "Reset password"
Applies to: Descendant User objects

The same seems to apply to situations where the permissions are set to apply to "Descendant *Computer* objects".

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/SharpHound/commit/95e6cb46fc84f12eb873e3cba38f27ecf99d1be4
