### ISSUE TITLE
When loading only the CSV files from a default collection method: the transitive object control(lers) fail to load. It works after uploading the users' props file

### ISSUE THREAD

**Issue by cnotin** [BloodHoundAD/SharpHound2#6]
The title says it all :)
Don't hesitate to ask if you need further information.

Neo4j 3.2.6 on Windows
SharpHound latest release
BloodHound latest release (1.4)
Same on Windows and Linux

**Comment by rvazarkar** [comment]
Fixed this in BloodHound already. Sorry for the mess up!

**Comment by cnotin** [comment]
(sorry for posting in the wrong repository).
I confirm, it works!
