### ISSUE TITLE
Sharphound doesn't enumerate anything

### ISSUE THREAD

**Issue by seanthegeek** [BloodHoundAD/SharpHound2#9]
```
PS C:\BloodHound\Ingestors> .\SharpHound.exe
Initializing BloodHound at 12:21 PM on 10/18/2017
Starting Default enumeration for example.net
Status: 0 objects enumerated (+0 0/s --- Using 53 MB RAM )
Status: 0 objects enumerated (+0 0/s --- Using 32 MB RAM )
Finished enumeration for example.net in 00:01:00.8284660
0 hosts failed ping. 0 hosts timedout.
```

The only file that gets generated is a 131 byte `BloodHound.bin` file. The old ingestor worked. What is going wrong?

**Comment by rvazarkar** [comment]
Try running with -Verbose

**Comment by seanthegeek** [comment]
```
PS C:\BloodHound\Ingestors> .\SharpHound.exe -v
Initializing BloodHound at 12:38 PM on 10/18/2017
Starting Default enumeration for example.net
Enumerating trusts for example.net
Status: 0 objects enumerated (+0 0/s --- Using 53 MB RAM )
Waiting for enumeration threads to finish
Status: 0 objects enumerated (+0 0/s --- Using 33 MB RAM )
Waiting for writer thread to finish
Finished enumeration for example.net in 00:01:00.5110998
0 hosts failed ping. 0 hosts timedout.
```

**Comment by rvazarkar** [comment]
Can you try with the --SecureLDAP flag? The only other time I've seen this behavior, SharpHound was unable to connect over regular LDAP.

**Comment by seanthegeek** [comment]
This is odd

```
PS C:\BloodHound\Ingestors> .\SharpHound.exe -v --SecureLDAP --IgnoreLdapCert
Initializing BloodHound at 12:44 PM on 10/18/2017
Ldap Connection Failure.
Try again with the IgnoreLdapCert option if using SecureLDAP or check your DomainController option
```

**Comment by rvazarkar** [comment]
Let me work on adding more verbosity to the output and I'll get back to you. My best guess is that SharpHound is grabbing a domain controller it cant properly connect to or something along those lines. I've never seen this particular behavior before. As for now, sticking with the old ingestor until we can fix this is probably the best bet.

If you manage to find any more info, let me know

**Comment by seanthegeek** [comment]
I'm happy to help debugging in any way I can. Thanks for such an awesome project!

**Comment by seanthegeek** [comment]
**Update** It turns out, manually specifying a `--domain-controller` _without_ `--SecureLDAP` works, FWIW.

**Comment by rvazarkar** [comment]
Interesting. So it looks like my theory was right, the Domain Controller grabbed by SharpHound was unreachable for one reason or another. I'll have to try and implement some logic to test for that scenario.

**Comment by seanthegeek** [comment]
More verbosity of TLS failures would be great too. I'd prefer to do this over a secure channel, if possible.

**Comment by rvazarkar** [comment]
All SharpHound LDAP communication is encrypted by default, whether its on SSL or not.

**Comment by MoawingWizard** [comment]
@rvazarkar I had the same issue today, and it still didn't work even after manually specifying the --DomainController flag. Also attempted --SecureLdap

**Comment by bravo2day** [comment]
Same issue here. 

.\SharpHound.exe -v
Initializing BloodHound at 18:27 on 16.02.2018
Starting enumeration for [REDACTED].local
Enumerating trusts for [REDACTED].local
Status: 0 objects enumerated (+0 0/s --- Using 41 MB RAM )
Waiting for enumeration threads to finish
Status: 0 objects enumerated (+0 0/s --- Using 32 MB RAM )
Waiting for writer thread to finish
Finished enumeration for [REDACTED].local in 00:01:00.3414154
0 hosts failed ping. 0 hosts timedout.
Deduplicating Files

Running https://raw.githubusercontent.com/BloodHoundAD/BloodHound/1.3/PowerShell/BloodHound.ps1 works fine.

**Comment by rvazarkar** [comment]
So as far as I can tell, sometimes SharpHound picks a domain controller which it can somehow bind to, but not get any data from. I'm completely at a loss as to what could be causing it. Hopefully I can run into this scenario myself so I can actually try and debug it.

Manually picking the Primary Domain Controller should generally work though

**Comment by stock99** [comment]
run into the same issue. At first it is working fine but after sometime, a non-stop 0 enumeration appeared. Below is just a log where it happen ( -verbose option is used).  Also attempted with -domaincontroller xxxxx.local  but same error is returned. 

Unable to resolve domain for FSP CN=S-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-1508,CN=ForeignSecurityPrincipals,DC=xxxxx,DC=local of
Unable to resolve domain for FSP CN=S-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-1412,CN=ForeignSecurityPrincipals,DC=xxxxx,DC=local
Unable to resolve domain for FSP CN=S-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-1309,CN=ForeignSecurityPrincipals,DC=xxxxx,DC=local
Unable to resolve domain for FSP CN=S-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-1405,CN=ForeignSecurityPrincipals,DC=xxxxx,DC=local
Unable to resolve domain for FSP CN=S-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-1399,CN=ForeignSecurityPrincipals,DC=xxxxx,DC=local
Unable to resolve domain for FSP CN=S-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-1359,CN=ForeignSecurityPrincipals,DC=xxxxx,DC=local
Unable to resolve domain for FSP CN=S-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-1280,CN=ForeignSecurityPrincipals,DC=xxxxx,DC=local
Status: 201637 objects enumerated (+7187 41.99021/s --- Using 219 MB RAM )
Status: 206228 objects enumerated (+4591 42.67963/s --- Using 182 MB RAM )
Waiting for enumeration threads to finish
Status: 214458 objects enumerated (+8230 44.10901/s --- Using 203 MB RAM )
Status: 214459 objects enumerated (+1 43.83871/s --- Using 202 MB RAM )
Status: 214459 objects enumerated (+0 43.57151/s --- Using 202 MB RAM )
Status: 214459 objects enumerated (+0 43.30755/s --- Using 202 MB RAM )
Status: 214459 objects enumerated (+0 43.04677/s --- Using 202 MB RAM )
Status: 214460 objects enumerated (+1 42.78931/s --- Using 202 MB RAM )
Status: 214460 objects enumerated (+0 42.53471/s --- Using 202 MB RAM )
Status: 214460 objects enumerated (+0 42.28312/s --- Using 193 MB RAM )
Status: 214460 objects enumerated (+0 42.0345/s --- Using 193 MB RAM )

**Comment by rvazarkar** [comment]
I know this issue has been open forever, but I think we've finally resolved it with https://github.com/BloodHoundAD/SharpHound/commit/49f905761533d9ae0f94e84e44ad514ff2c304c3

**Comment by c3101** [comment]
I've tried all sorts of combination of flags, but nothing seems to work :(

D:\Ingestor>SharpHound.exe -c All -d XXX.XX.XX --JsonFolder D:\Scans\%scandate% --ZipFileName XXX.XX.XX-%scandate%.zip --CacheFile D:\Ingestor\CACHEFILE.bin
Initializing BloodHound at 04:29 PM on 2019/09/05
Ldap Connection Failure.
Try again with the IgnoreLdapCert option if using SecureLDAP or check your DomainController/LdapPort option


The DC really is at 192.19.0.4!

D:\Ingestor>ping 192.19.0.4

Pinging 192.19.0.4 with 32 bytes of data:
Reply from 192.19.0.4: bytes=32 time=1ms TTL=123
Reply from 192.19.0.4: bytes=32 time=1ms TTL=123

SharpHound.exe -c All -d XXX.XX.XX --JsonFolder D:\Scans\%scandate% --ZipFileName XXX.XX.XX-%scandate%.zip --CacheFile D:\Ingestor\CACHEFILE.bin --DomainController 192.19.0.4 
Initializing BloodHound at 04:31 PM on 2019/09/05
Manually specifying a domain controller will likely result in data loss. Only use this for performance/opsec reasons
Ldap Connection Failure.
Try again with the IgnoreLdapCert option if using SecureLDAP or check your DomainController/LdapPort option


SharpHound.exe -c All -d XXX.XX.XX --JsonFolder D:\Scans\%scandate% --ZipFileName XXX.XX.XX-%scandate%.zip --CacheFile D:\Ingestor\CACHEFILE.bin --DomainController 192.19.0.4 --IgnoreLdapCert
Initializing BloodHound at 04:31 PM on 2019/09/05
Manually specifying a domain controller will likely result in data loss. Only use this for performance/opsec reasons
Ldap Connection Failure.
Try again with the IgnoreLdapCert option if using SecureLDAP or check your DomainController/LdapPort option

**Comment by whitecod** [comment]
I am having the same problem. I isolated the issue to the Kerberos Signing part. If I disable it with `--DisableKerbSigning` it works but not ideal. Is it possible that it is caused by the machine not being domain joined and not trusting the server certificate?

**Comment by c3101** [comment]
> I am having the same problem. I isolated the issue to the Kerberos Signing part. If I disable it with `--DisableKerbSigning` it works but not ideal. Is it possible that it is caused by the machine not being domain joined and not trusting the server certificate?

Tried it, didn't work :( same failure

**Comment by whitecod** [comment]
> > I am having the same problem. I isolated the issue to the Kerberos Signing part. If I disable it with `--DisableKerbSigning` it works but not ideal. Is it possible that it is caused by the machine not being domain joined and not trusting the server certificate?
> 
> Tried it, didn't work :( same failure

Use Wireshark to check what part fails. I would also try using the FQDN instead of IP address or removing the `-d` option entirely.
